version: "3"
services:
  postgres:
    image: postgres:11.2-alpine
    container_name: cosmobots_postgres
    environment:
      - POSTGRES_USER=cosmobot
      - POSTGRES_PASSWORD=cosmobotisthesecretword
      - POSTGRES_DB=cosmobots
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local
